apiVersion: v1
kind: Secret
metadata: 
  name: backend-secret
data:
  .env: "REFUQUJBU0VfVVJMPXBvc3RncmVzOi8vb2Frb2ZhbgpBV1NfU0VDUkVUPW5qYWRudmprbGRhbnYKUE9SVD0zMDAwClBVQkxJQ19LRVk9MTIzMzJuam5qc3ZkCkpXVF9TRUNSRVQ9MTJmbmpkYmYganNr" 